### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by kanojia-gaurav** [csrohit/fresco-play#16]
![Screenshot 2021-08-12 194844](https://user-images.githubusercontent.com/60805839/129713701-10f3d792-8cd1-4b3e-a9ec-37053a9374dc.jpg)

Bro yeh question get ka he solve ho raha hai post nhi horaha kyu?

const http = require('http');
const url = require('url');

const server = http.createServer((req, res) => {

    const urlobj = url.parse(req.url, true);
    const hostname = urlobj.host;
    const pathname = urlobj.pathname;
    const serch = urlobj.serch;
    const qureydata = urlobj.query;
    //console.log(qureydata);

    if (pathname === '/cal' && req.method === 'GET') {

        if (qureydata.func === 'add') {
            res.writeHead(200, { "Content-Type": "text/plain" });
            result = parseInt(qureydata.a) + parseInt(qureydata.b)
            res.write(`Addition is: ${result}`);
			console.log(result);
            res.end();
        } else if (qureydata.func === 'subtract') {
            res.writeHead(200, { "Content-Type": "text/plain" });
            result = parseInt(qureydata.a) - parseInt(qureydata.b)
            res.write(`Subtraction is: ${result}`);
			console.log(result);
            res.end();
        }

    } else if (pathname === '/cal' && req.method === 'POST') {
        if (qureydata.func === 'multiple') {
            var body = "";
            req.on("data", function (chunk) {
                body += chunk;
            });

            req.on("end", function () {
                res.writeHead(200, { "Content-Type": "text/plain" });
                result = parseInt(qureydata.a) * parseInt(qureydata.b)
                res.write(`Multiplication is: ${result}`);
                console.log(result);
                res.end();
            });

        } else {
            //console.log(qureydata.func);
            var body = "";
            req.on("data", function (chunk) {
                body += chunk;
            });

            req.on("end", function () {
                res.writeHead(200, { "Content-Type": "text/plain" });
                result = parseInt(qureydata.a) / parseInt(qureydata.b)
				res.write(`Division is: ${result}`);
				console.log(result);
                res.end();
            });

        }

    }

}).listen(8000);

this is the code i have written please help me bro

**Comment by kanojia-gaurav** [comment]
![WhatsApp Image 2021-08-12 at 4 41 29 PM](https://user-images.githubusercontent.com/60805839/129714323-997710e9-4221-41c2-a89a-17f7c2d07d00.jpeg)

Bro yeh question bhi kiya me kya galat hai help karna jara.


process.stdin.resume();
process.stdin.setEncoding("ascii");
var input = "";
process.stdin.on("data", function (chunk) {
    input += chunk;
});



process.stdin.on("end", function () {
    
    input = input.split(" ");
    n1 = input[0];
    n2 = input[1];
    
    function consoleee(sum){
    setTimeout(()=>console.log(sum) , 2000);
    }


    function sum1(n1, n2, mycallback){

        let sum =0;
        for (let i=0; i<=1000 ; i++){
            if(i%n1 === 0){
                sum = sum + i;
            }
            if(i%n2 === 0){
                sum = sum + i;
            }
        }
        mycallback(sum)
    }

    sum1(n1, n2, consoleee);
    
    
    const EventEmitter =  require('events');
    var MyEvent = new EventEmitter();
    
    MyEvent.on('LogInfo',()=>{
        console.log(`Multiples of ${n1} & ${n2}`);
    });
    
    MyEvent.emit('LogInfo');
    
});


yeh code hai kya wrong hai bro help karna jara mera t factor increase hojayega help karde bro kabse yeh question me he atka hu

**Comment by abisep** [comment]
Please help me with callbacks and events handson I have been trying but unable to pass test cases(Logic is Correct also used callbacks and events )

**Comment by csrohit** [comment]
look at the testcases. Try to match them but the problem description.

**Comment by csrohit** [comment]
solutions are only for reference. You should try to solve the handson by yourself.
